from __future__ import annotations

CPG_NODE_SCHEMA: dict[str, frozenset[str]] = {
    "ANNOTATION": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER FULL_NAME LINE_NUMBER NAME OFFSET OFFSET_END ORDER".split()
    ),
    "ANNOTATION_LITERAL": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER LINE_NUMBER NAME OFFSET OFFSET_END ORDER".split()
    ),
    "ANNOTATION_PARAMETER": frozenset(
        "CODE COLUMN_NUMBER LINE_NUMBER OFFSET OFFSET_END ORDER".split()
    ),
    "ANNOTATION_PARAMETER_ASSIGN": frozenset(
        "CODE COLUMN_NUMBER LINE_NUMBER OFFSET OFFSET_END ORDER".split()
    ),
    "ARRAY_INITIALIZER": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER LINE_NUMBER OFFSET OFFSET_END ORDER".split()
    ),
    "BINDING": frozenset("METHOD_FULL_NAME NAME SIGNATURE".split()),
    "BLOCK": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME LINE_NUMBER OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "CALL": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER DISPATCH_TYPE DYNAMIC_TYPE_HINT_FULL_NAME LINE_NUMBER METHOD_FULL_NAME NAME OFFSET OFFSET_END ORDER POSSIBLE_TYPES SIGNATURE STATIC_RECEIVER TYPE_FULL_NAME".split()
    ),
    "CLOSURE_BINDING": frozenset("CLOSURE_BINDING_ID EVALUATION_STRATEGY".split()),
    "COMMENT": frozenset(
        "CODE COLUMN_NUMBER FILENAME LINE_NUMBER OFFSET OFFSET_END ORDER".split()
    ),
    "CONFIG_FILE": frozenset("CONTENT NAME".split()),
    "CONTROL_STRUCTURE": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER CONTROL_STRUCTURE_TYPE LINE_NUMBER OFFSET OFFSET_END ORDER PARSER_TYPE_NAME".split()
    ),
    "DEPENDENCY": frozenset("DEPENDENCY_GROUP_ID NAME VERSION".split()),
    "FIELD_IDENTIFIER": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CANONICAL_NAME CODE COLUMN_NUMBER LINE_NUMBER OFFSET OFFSET_END ORDER".split()
    ),
    "FILE": frozenset(
        "CODE COLUMN_NUMBER CONTENT HASH LINE_NUMBER NAME OFFSET OFFSET_END ORDER".split()
    ),
    "FINDING": frozenset("EVIDENCE_DESCRIPTION".split()),
    "IDENTIFIER": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME LINE_NUMBER NAME OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "IMPORT": frozenset(
        "CODE COLUMN_NUMBER EXPLICIT_AS IMPORTED_AS IMPORTED_ENTITY IS_EXPLICIT IS_MODULE_IMPORT IS_WILDCARD LINE_NUMBER OFFSET OFFSET_END ORDER".split()
    ),
    "JUMP_LABEL": frozenset(
        "CODE COLUMN_NUMBER LINE_NUMBER NAME OFFSET OFFSET_END ORDER PARSER_TYPE_NAME".split()
    ),
    "JUMP_TARGET": frozenset(
        "ARGUMENT_INDEX CODE COLUMN_NUMBER LINE_NUMBER NAME OFFSET OFFSET_END ORDER PARSER_TYPE_NAME".split()
    ),
    "KEY_VALUE_PAIR": frozenset("KEY VALUE".split()),
    "LITERAL": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME LINE_NUMBER OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "LOCAL": frozenset(
        "CLOSURE_BINDING_ID CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME GENERIC_SIGNATURE LINE_NUMBER NAME OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "MEMBER": frozenset(
        "AST_PARENT_FULL_NAME AST_PARENT_TYPE CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME GENERIC_SIGNATURE LINE_NUMBER NAME OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "META_DATA": frozenset("HASH LANGUAGE OVERLAYS ROOT VERSION".split()),
    "METHOD": frozenset(
        "AST_PARENT_FULL_NAME AST_PARENT_TYPE CODE COLUMN_NUMBER COLUMN_NUMBER_END FILENAME FULL_NAME GENERIC_SIGNATURE HASH IS_EXTERNAL LINE_NUMBER LINE_NUMBER_END NAME OFFSET OFFSET_END ORDER SIGNATURE".split()
    ),
    "METHOD_PARAMETER_IN": frozenset(
        "CLOSURE_BINDING_ID CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME EVALUATION_STRATEGY INDEX IS_VARIADIC LINE_NUMBER NAME OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "METHOD_PARAMETER_OUT": frozenset(
        "CODE COLUMN_NUMBER EVALUATION_STRATEGY INDEX IS_VARIADIC LINE_NUMBER NAME OFFSET OFFSET_END ORDER TYPE_FULL_NAME".split()
    ),
    "METHOD_REF": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME LINE_NUMBER METHOD_FULL_NAME OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "METHOD_RETURN": frozenset(
        "CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME EVALUATION_STRATEGY LINE_NUMBER OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "MODIFIER": frozenset(
        "CODE COLUMN_NUMBER LINE_NUMBER MODIFIER_TYPE OFFSET OFFSET_END ORDER".split()
    ),
    "NAMESPACE": frozenset(
        "CODE COLUMN_NUMBER LINE_NUMBER NAME OFFSET OFFSET_END ORDER".split()
    ),
    "NAMESPACE_BLOCK": frozenset(
        "CODE COLUMN_NUMBER FILENAME FULL_NAME LINE_NUMBER NAME OFFSET OFFSET_END ORDER".split()
    ),
    "RETURN": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER LINE_NUMBER OFFSET OFFSET_END ORDER".split()
    ),
    "LOCATION": frozenset(
        "CLASS_NAME CLASS_SHORT_NAME FILENAME LINE_NUMBER METHOD_FULL_NAME METHOD_SHORT_NAME NODE_LABEL PACKAGE_NAME SYMBOL".split()
    ),
    "TAG": frozenset("NAME VALUE".split()),
    "TAG_NODE_PAIR": frozenset(),
    "TEMPLATE_DOM": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER LINE_NUMBER NAME OFFSET OFFSET_END ORDER".split()
    ),
    "TYPE": frozenset("FULL_NAME NAME TYPE_DECL_FULL_NAME".split()),
    "TYPE_ARGUMENT": frozenset(
        "CODE COLUMN_NUMBER LINE_NUMBER OFFSET OFFSET_END ORDER".split()
    ),
    "TYPE_DECL": frozenset(
        "ALIAS_TYPE_FULL_NAME AST_PARENT_FULL_NAME AST_PARENT_TYPE CODE COLUMN_NUMBER FILENAME FULL_NAME GENERIC_SIGNATURE INHERITS_FROM_TYPE_FULL_NAME IS_EXTERNAL LINE_NUMBER NAME OFFSET OFFSET_END ORDER".split()
    ),
    "TYPE_PARAMETER": frozenset(
        "CODE COLUMN_NUMBER LINE_NUMBER NAME OFFSET OFFSET_END ORDER".split()
    ),
    "TYPE_REF": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER DYNAMIC_TYPE_HINT_FULL_NAME LINE_NUMBER OFFSET OFFSET_END ORDER POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
    "UNKNOWN": frozenset(
        "ARGUMENT_INDEX ARGUMENT_LABEL ARGUMENT_NAME CODE COLUMN_NUMBER CONTAINED_REF DYNAMIC_TYPE_HINT_FULL_NAME LINE_NUMBER OFFSET OFFSET_END ORDER PARSER_TYPE_NAME POSSIBLE_TYPES TYPE_FULL_NAME".split()
    ),
}

CPG_EDGE_LABELS: frozenset[str] = frozenset(
    """
    ALIAS_OF ARGUMENT AST BINDS BINDS_TO CALL CAPTURE CAPTURED_BY CATCH_BODY CDG
    CFG CONDITION CONTAINS DO_BODY DOMINATE EVAL_TYPE FALSE_BODY FINALLY_BODY
    FOR_BODY FOR_INIT FOR_UPDATE IMPORTS INHERITS_FROM IS_CALL_FOR_IMPORT
    PARAMETER_LINK POST_DOMINATE REACHING_DEF RECEIVER REF SOURCE_FILE TAGGED_BY
    TRUE_BODY TRY_BODY
    """.split()
)


def property_to_attr(name: str) -> str:
    return name.lower()


def label_to_class_name(label: str) -> str:
    return "".join(part.title() for part in label.lower().split("_"))


def label_to_step_name(label: str) -> str:
    name = label.lower()
    return {
        "meta_data": "meta_data",
        "type": "type",
        "return": "return_",
        "file": "file",
    }.get(name, name)


def build_node_classes(base_cls: type) -> dict[str, type]:
    classes: dict[str, type] = {}
    for label, properties in CPG_NODE_SCHEMA.items():
        attrs = {
            "schema_label": label,
            "schema_properties": properties,
            "__module__": "cpg.objects",
        }
        classes[label] = type(label_to_class_name(label), (base_cls,), attrs)
    return classes


def schema_property_aliases(label: str) -> dict[str, str]:
    return {property_to_attr(prop): prop for prop in CPG_NODE_SCHEMA[label]}
