name: Docs

on:
  push:
    branches: [master]
    paths:
      - pyproject.toml
      - scubatrace/**
      - docs/**

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deploy.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get install -y libgraphviz-dev
      - name: Install
        run: pip install -e .[docs]
      - name: Build docs
        run: sphinx-build -M html docs docs/_build
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
