name: Tests

on:
  push:
    branches: [master]
    paths:
      - pyproject.toml
      - scubatrace/**
      - tests/**

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get install -y libgraphviz-dev
      - name: Install
        run: pip install -v -e .
      - name: Test
        run: python -munittest -v
